services:
  # Servicio de desarrollo
  dev:
    build:
      context: .
      target: builder
    command: npm run dev -- -p 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    networks:
      - agendia-network

  # Servicio de producción
  prod:
    build:
      context: .
      target: runner
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - agendia-network

networks:
  agendia-network:
    driver: bridge 